// examples/react/src/App.js
import React from "react";

import image from "./assets/Macaca_nigra_self-portrait_large.jpg";
import imageSrcSetWebp from "./assets/Macaca_nigra_self-portrait_large.jpg?srcset&format=webp&quality=90";
import imageSrcSet from "./assets/Macaca_nigra_self-portrait_large.jpg?srcset&quality=90";

function App() {
  return (
    <div>
      <img style={{ width: "50vw" }} srcSet={imageSrcSet} src={image} />

      {/* for modern browsers: */}
      <picture>
        <source type="image/webp" srcSet={imageSrcSetWebp} />
        <source type="image/jpeg" srcSet={imageSrcSet} />
        <img style={{ width: "50vw" }} src={image} />
      </picture>
    </div>
  );
}

export default App;

// examples/vue/src/App.vue
<template>
  <div>
    <img
      style="width: 50vw"
      src="@/assets/Macaca_nigra_self-portrait_large.jpg"
      :srcset="
        require('@/assets/Macaca_nigra_self-portrait_large.jpg?srcset&quality=100')
      "
    />
    <!-- for modern browsers: -->
    <picture>
      <source
        type="image/webp"
        :srcset="
          require('@/assets/Macaca_nigra_self-portrait_large.jpg?srcset&format=webp&quality=100')
        "
      />
      <source
        type="image/jpeg"
        :srcset="
          require('@/assets/Macaca_nigra_self-portrait_large.jpg?srcset&quality=100')
        "
      />
      <img
        style="width: 50vw"
        src="@/assets/Macaca_nigra_self-portrait_large.jpg"
      />
    </picture>
  </div>
</template>
